proxy:
  title: MS-Nutrition Shiny applications
  logo-url: https://ms-nutrition.com/wp-content/themes/msnutrition/images/logo.png
  port: 8080

  container-wait-time: 30000
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-log-path: ./container-logs

  authentication: none

  docker:
      internal-networking: true

  specs:
  - id: test_manager
    display-name: test_manager
    description: Application test
    container-cmd: ["R", "-e", "shiny::runApp('/root/test_shinymanager')"]
    container-image: rzngzn/test_shinymanager:v0
    container-network: sp-net
  - id: bkfst
    display-name: breakfast application
    description: Make your breakfast
    container-cmd: ["R", "-e", "shiny::runApp('/root/breakfast_demo')"]
    container-image: rzngzn/bkfst:latest
    container-network: sp-net

logging:
  file:
    /log/shinyproxy.log


