name: Publish on Server host

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy_serveur')" 
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
           port: 22
           script: |
              ${{ secrets.SERVER_CMD_UPDATE_DOCKER }}
