name: Publish on Server host

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')" 
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
           host: ubuntu@51.68.88.177
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
           port: 22
           script: |
             cd test_manager
             sudo docker-compose down
