name: Publish on Server host

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')" 
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
           host: 51.68.88.177
           username: ubuntu
           key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
           port: 22
           script: |
             cd test_manager
             sudo docker-compose down
             cd ..
             sudo rm -r -f  test_manager
             git clone  https://github.com/RozennGZ/test_manager.git
             docker rm -f $(docker ps -a -q)
             docker rmi -f $(docker images -a -q)
             docker system prune -f
             docker images purge
             cd test_manager
             chmod +x init-letsencrypt.sh
             sudo ./init-letsencrypt.sh
             sudo docker-compose up
